services:
  kalilinux:
    hostname: localhost
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'csalab/kalilinux-docker:slim'
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - SHELL=/bin/bash
      - PASSWORD=${PASSWORD:-kalilinux}
    env_file:
      - .env
    volumes:
      - data:/home/kali/Desktop
    entrypoint: ["/bin/bash", "/startup.sh"]

volumes:
  data: {}